LoongArch: eBPF: Restrict bpf_probe_read{, str}() only to archs where they work
When we run nettrace on LoongArch, there is a problem that
ERROR: failed to load kprobe-based eBPF
ERROR: failed to load kprobe-based bpf

Because ARCH_HAS_NON_OVERLAPPING_ADDRESS_SPACE dose not exist,
so we enable it.

The patch reference upstream id 0ebeea8ca8a4d1d453ad299aef0507dab04f6e8d.

Signed-off-by: zhaochenguang <zhaochenguang@kylinos.cn>