bpf/scripts: Generate GCC compatible helpers
The current bpf_helper_defs.h helpers are llvm specific and don't work
correctly with gcc.

GCC appears to required kernel helper funcs to have the following
attribute set: __attribute__((kernel_helper(NUM)))

Generate gcc compatible headers based on the format in bpf-helpers.h.

This generates GCC/Clang compatible helpers, for example:
	/* Helper macro for GCC/Clang compatibility */
	#define NOARG
	#if __GNUC__ && !__clang__
	#define BPF_HELPER_DEF(num, ret_star, ret_type, name, ...) \
	ret_type ret_star name(__VA_ARGS__) __attribute__((kernel_helper(num)));
	#else
	#define BPF_HELPER_DEF(num, ret_star, ret_type, name, ...) \
	static ret_type ret_star(*name)(__VA_ARGS__) = (void *) num;
	#endif

	BPF_HELPER_DEF(1, *, void, bpf_map_lookup_elem, void *map, const void *key)

	BPF_HELPER_DEF(2, NOARG, long, bpf_map_update_elem, void *map, const void *key, const void *value, __u64 flags)

See:
https://github.com/gcc-mirror/gcc/blob/releases/gcc-12.1.0/gcc/config/bpf/bpf-helpers.h#L24-L27

This fixes the following build error:
error: indirect call in function, which are not supported by eBPF

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>