btf: Fix required space error
This patch fixes error reported ny Checkpatch at bpf_log()

ERROR: space required after that , ctx:VxV
Signed-off-by: Jules Irenge <jbi.octave@gmail.com>