bpftool: Fix build with OpenSSL versions older than 3.0
ERR_get_error_all() exists only in OpenSSL 3.0 and later. Older versions
lack this API, causing build failure:

  sign.c: In function 'display_openssl_errors':
  sign.c:40:21: warning: implicit declaration of function 'ERR_get_error_all'; did you mean 'ERR_get_error_line'? [-Wimplicit-function-declaration]
     40 |         while ((e = ERR_get_error_all(&file, &line, NULL, &data, &flags))) {
        |                     ^~~~~~~~~~~~~~~~~
        |                     ERR_get_error_line
  LINK    /tmp/build/perf/util/bpf_skel/.tmp/bootstrap/bpftool
  /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/build/perf/util/bpf_skel/.tmp/bootstrap/sign.o: in function `display_openssl_errors.constprop.0':
  sign.c:(.text+0x59): undefined reference to `ERR_get_error_all'
  collect2: error: ld returned 1 exit status

Use the deprecated ERR_get_error_line_data() for OpenSSL < 3.0, and keep
using ERR_get_error_all() when available.

Fixes: 40863f4d6ef2 ("bpftool: Add support for signing BPF programs")
Signed-off-by: Leo Yan <leo.yan@arm.com>