selftests/bpf: Fix a testmod compilation failure due to missing const modifier
Commit 97d06802d10a ("sysfs: constify bin_attribute argument of bin_attribute::read/write()")
added constant modifier to 'struct bin_attribute *' for read/write
func pointer members. This caused compilation failure with clang20:

   bpf_testmod.c:494:10: error: incompatible function pointer types initializing
  'ssize_t (*)(struct file *, struct kobject *, const struct bin_attribute *, char *, loff_t, size_t)'
  (aka 'long (*)(struct file *, struct kobject *, const struct bin_attribute *,
                 char *, long long, unsigned long)')
  with an expression of type 'ssize_t (struct file *, struct kobject *, struct bin_attribute *,
                                       char *, loff_t, size_t)'
  (aka 'long (struct file *, struct kobject *, struct bin_attribute *, char *, long long, unsigned long)')
  [-Wincompatible-function-pointer-types]
  494 |         .read = bpf_testmod_test_read,
      |                 ^~~~~~~~~~~~~~~~~~~~~
  ...

The same compilation error for functions bpf_testmod_test_write() and bpf_testmod_uprobe_write().

Fix the build failure by adding proper 'const' modifier.

Signed-off-by: Yonghong Song <yonghong.song@linux.dev>